apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  generation: 1
  labels:
    app: YOUR-LABEL
  name: ssl-tls-ingress
  namespace: default
  ownerReferences:
  - apiVersion: networking.k8s.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Ingress
spec:
  dnsNames:
  - DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: ssl-tls-ingress
  usages:
  - digital signature
  - key encipherment
